server:
  port : 8088

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST



      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            #- AuthenticationFilter


        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - RewritePath=/api/v1/product/(?<productId>.*), /api/v1/product/${productId}

        ## AUTH service
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            #- AuthenticationFilter


        ## CATEGORY service
        - id: category
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**
          filters:
            #- AuthenticationFilter

        - id: category
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**
          filters:
            - RewritePath=/api/v1/category/(?<id>.*), /api/v1/category/${id}


        ## CART service
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            #- AuthenticationFilter

        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - RewritePath=/api/v1/cart/(?<cartId>.*), /api/v1/cart/${cartId}



application:
  name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

